# Generated by Django 4.1.2 on 2022-11-14 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name='数量')),
                ('type', models.SmallIntegerField(blank=True, choices=[(0, '入库'), (1, '出库')], default=0, verbose_name='类型')),
                ('creater', models.CharField(max_length=255, verbose_name='Who created')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Update Time')),
                ('good', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='goods.listmodel', verbose_name='商品')),
            ],
            options={
                'verbose_name': '出入库表',
                'verbose_name_plural': '出入库表',
                'db_table': 'in_out_warehouse',
            },
        ),
    ]
